language: python
python:
  - "3.10"

install:
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls

before_script:
  - black --check .
  - flake8 .

script:
  - coverage run manage.py test
